# Transfer Learning

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import Model
from tensorflow.keras.models import Sequential
tf.__version__

'2.9.1'

## Load an empty dataset for user input

In [2]:
%cd Z:\PPMI_Data\Excels\CollaborativeFiltering
df2 = pd.read_csv('NonMotor_Empty.csv')
# Removing a column
df3 = df2.drop('Patient_ID', axis = 1)
df3.head(2)

Z:\PPMI_Data\Excels\CollaborativeFiltering


Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  Constipate  Depress  \
0      NaN     NaN     NaN    NaN        NaN       NaN         NaN      NaN   

   DopaDefic  Education  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
0        NaN        NaN  ...       NaN       NaN         NaN    NaN    NaN   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
0           NaN             NaN             NaN    NaN    NaN  

[1 rows x 45 columns]

## Take input from user

In [3]:
# Ask the user for the updated value of age
new_age = int(input("What is the user's age (in years): "))

# Update the value of age in the dataframe
df3.at[0, 'Age'] = new_age

# Print the updated dataframe
print(df3)


What is the user's age (in years): 44
   Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  Constipate  Depress  \
0      NaN     NaN     NaN    NaN        NaN       NaN         NaN      NaN   

   DopaDefic  Education  ...  SleepDay  SleepNight  STAIA  STAIS  \
0        NaN        NaN  ...       NaN         NaN    NaN    NaN   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine   Age  
0           NaN             NaN             NaN    NaN    NaN  44.0  

[1 rows x 46 columns]


## Loading Sparse Full data

In [4]:
dframe1 = pd.read_csv('Feats45_unCategSparse_APPRDX.csv')
# dropping a few columns
dframe = dframe1.drop(['PATNO','APPRDX','Age'], axis = 1)
dframe = dframe.add(1)
print(dframe.shape)
dframe.head(2)

(618, 47)


Patient_ID  Gender  Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  \
0           2       2        2       1   16.46    NaN          1       2.0   
1           3       1        2       1   13.16    8.0          2       2.0   

   Constipate  Depress  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
0           1        1  ...        50         2           1     48     45   
1           2        2  ...        58         2           1     46     60   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
0     49.330002            54.0            91.0     26    5.0  
1     48.500000           111.0           205.0     18    2.0  

[2 rows x 47 columns]

## Taking input from user

In [5]:
def update_values(df3, dframe):
    # Input from the user for number of columns
    num_columns = int(input("Enter the number of columns you want to update (minimum 3, maximum 45): "))
    
    while num_columns < 3 or num_columns > 45:
        print("Invalid number of columns. Please enter a number between 3 and 45.")
        num_columns = int(input("Enter the number of columns you want to update (minimum 3, maximum 45): "))
    
    columns = []
    values = []
     
    # Loop to get input from the user for each column
    for i in range(num_columns):
        column = input("Enter the name of the Feature %d: " % (i + 1))
        value = input("Enter the score of the Feature %d: " % (i + 1))
        
        columns.append(column)
        values.append(int(value)) 
        
    # Update the values in the dataframe
    for i in range(num_columns):
        df3.loc[df3[columns[i]] != values[i], columns[i]] = values[i] 
    
    # Put values equal to zero on the columns that are not selected
    for col in dframe.columns:
        if col not in columns and col != 'Age': # Skip 'Age' column
            dframe = dframe.drop(col, axis=1)
    
    return df3, dframe

# Call the function
df3, dframe = update_values(df3, dframe)

# Print the updated dataframe and the modified dframe
print("\nUpdated dataframe:\n")
print(df3.head())

print("\nModified dataframe:\n")
print(dframe.head())


Enter the number of columns you want to update (minimum 3, maximum 45): 3
Enter the name of the Feature 1: UPSIT
Enter the score of the Feature 1: 9
Enter the name of the Feature 2: Clock
Enter the score of the Feature 2: 3
Enter the name of the Feature 3: Pain
Enter the score of the Feature 3: 2

Updated dataframe:

   Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  Constipate  Depress  \
0      NaN     NaN     NaN    3.0        NaN       NaN         NaN      NaN   

   DopaDefic  Education  ...  SleepDay  SleepNight  STAIA  STAIS  \
0        NaN        NaN  ...       NaN         NaN    NaN    NaN   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine   Age  
0           NaN             NaN             NaN    9.0    NaN  44.0  

[1 rows x 46 columns]

Modified dataframe:

   Clock  Pain  UPSIT
0    NaN   1.0     26
1    8.0   2.0     18
2    NaN   2.0     24
3    NaN   2.0     14
4    NaN   3.0     19


## Moving Age column (as the first column)

In [6]:
col_age = df3.pop('Age')
df3.insert(0, "Age", col_age)
df3.head()

Age  Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  Constipate  \
0  44.0      NaN     NaN     NaN    3.0        NaN       NaN         NaN   

   Depress  DopaDefic  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
0      NaN        NaN  ...       NaN       NaN         NaN    NaN    NaN   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
0           NaN             NaN             NaN    9.0    NaN  

[1 rows x 46 columns]

In [7]:
# dropping a few columns
df3 = df3.dropna(axis = 1)
print(df3.shape)
df3.head(2)

(1, 4)


Age  Clock  Pain  UPSIT
0  44.0    3.0   2.0    9.0

## Removing NaN values, taking only those who have score for features given as input

In [8]:
# dropping a few columns
dframe = dframe.dropna()
print(dframe.shape)
dframe.head(2)

(284, 3)


Clock  Pain  UPSIT
1    8.0   2.0     18
5    7.0   3.0     10

### Adding Age Column to it

In [9]:
# Drop the Age column from the original DataFrame
col_age = dframe1.pop('Age')

# Insert the column at the 1st position
dframe.insert(0, "Age", col_age)
dframe.head(2)

Age  Clock  Pain  UPSIT
1  67.578082    8.0   2.0     18
5  46.965716    7.0   3.0     10

### Adding APPRDX column as 1st column

In [10]:
col_Apprdx = dframe1.pop('APPRDX')
dframe.insert(0, 'APPRDX', col_Apprdx)

In [11]:
dframes = dframe.drop(['APPRDX'], axis = 1)
print(dframes.shape)
dframes.head(2)

(284, 4)


Age  Clock  Pain  UPSIT
1  67.578082    8.0   2.0     18
5  46.965716    7.0   3.0     10

## Changing APPRDX values from 1 & 2 to 0 & 1

In [12]:
dframe.loc[:, "APPRDX"] = dframe["APPRDX"].apply(lambda x: x - 1)
dframe.head(2)

APPRDX        Age  Clock  Pain  UPSIT
1       0  67.578082    8.0   2.0     18
5       0  46.965716    7.0   3.0     10

## Creating Test Train Dataset

In [13]:
X = dframe.iloc[:, 1:].values
y = dframe.iloc[:, 0].values

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [15]:
X_train

array([[56.32054795,  8.        ,  1.        , 28.        ],
       [66.6276368 ,  7.        ,  2.        , 28.        ],
       [71.11780822,  6.        ,  1.        ,  9.        ],
       [57.53972603,  8.        ,  1.        , 21.        ],
       [62.64979415,  8.        ,  3.        , 22.        ],
       [55.99726776,  7.        ,  1.        , 37.        ],
       [41.56712329,  8.        ,  2.        , 31.        ],
       [67.08634628,  5.        ,  2.        , 17.        ],
       [49.97260274,  8.        ,  2.        , 16.        ],
       [68.51780822,  8.        ,  1.        , 23.        ],
       [37.24657534,  8.        ,  2.        , 36.        ],
       [48.2295082 ,  7.        ,  1.        , 30.        ],
       [60.49589041,  6.        ,  3.        , 39.        ],
       [46.00678195,  8.        ,  1.        , 27.        ],
       [62.84528782,  2.        ,  1.        , 15.        ],
       [49.58170522,  8.        ,  4.        , 37.        ],
       [53.59452055,  8.

In [16]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0], dtype=int64)

## Removing 1st layer of the model, replacing with dframe

In [17]:
from keras.models import load_model, Model
from keras.layers import Input, Dense

# Load the pre-trained model
model_ann = load_model('model_ann.h5')

# Define the input layer of the new model with a different shape
new_input_layer = Input(shape=dframes.shape[1:])
#new_input_layer = Dense(units = 13, input_shape=(dframes.shape[1:]), activation='relu')

# Define the first hidden layer of the new model
new_hidden_layer1 = Dense(units=12, activation='relu',kernel_regularizer=tf.keras.regularizers.l1(0.01))(new_input_layer)

# Get the weights of the second hidden and output layers from the pre-trained model
pretrained_hidden_layer2_weights = model_ann.layers[1].get_weights()
pretrained_output_layer_weights = model_ann.layers[2].get_weights()

# Define the second hidden layer and the output layer of the new model using the pre-trained weights
new_hidden_layer2 = Dense(units=pretrained_hidden_layer2_weights[0].shape[1], activation='relu', weights=pretrained_hidden_layer2_weights)(new_hidden_layer1)
new_output_layer = Dense(units=pretrained_output_layer_weights[0].shape[1], activation='sigmoid', weights=pretrained_output_layer_weights)(new_hidden_layer2)


# Create the new model with the input layer and all four layers
new_model = Model(inputs=new_input_layer, outputs=new_output_layer)

# Compile the new model with the desired optimizer, loss function, and metrics
new_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

for layer in new_model.layers[2:]:
    layer.trainable = False

In [18]:
new_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 12)                60        
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 173
Trainable params: 60
Non-trainable params: 113
_________________________________________________________________


In [19]:
new_model.fit(X_train, y_train, batch_size = 20, epochs = 100)

Epoch 1/100
12/12 [==============================] - 1s 1ms/step - loss: 0.7201 - accuracy: 0.6740
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6695 - accuracy: 0.7093
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6337 - accuracy: 0.7797
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 0.6220 - accuracy: 0.7841
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6028 - accuracy: 0.7930
Epoch 6/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5954 - accuracy: 0.8282
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5905 - accuracy: 0.7974
Epoch 8/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5834 - accuracy: 0.8062
Epoch 9/100
12/12 [==============================] - 0s 592us/step - loss: 0.5814 - accuracy: 0.8106
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5653 - accuracy: 0.8326
Epoch 1

12/12 [==============================] - 0s 1ms/step - loss: 0.4792 - accuracy: 0.8458
Epoch 83/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4716 - accuracy: 0.8062
Epoch 84/100
12/12 [==============================] - 0s 592us/step - loss: 0.4740 - accuracy: 0.8546
Epoch 85/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4683 - accuracy: 0.8502
Epoch 86/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4663 - accuracy: 0.8458
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4750 - accuracy: 0.8150
Epoch 88/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4696 - accuracy: 0.8326
Epoch 89/100
12/12 [==============================] - 0s 592us/step - loss: 0.4694 - accuracy: 0.8414
Epoch 90/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4756 - accuracy: 0.8238
Epoch 91/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4678 - accuracy: 0.8414
Epoch 92/

In [51]:
import pandas as pd

# Predict the outcome of the df3 data frame
prediction = new_model.predict(df3,verbose=0)

# Determine the predicted class and scaled prediction
if prediction[0][0] > 0.5:
    predicted_class = "Healthy"
    scaled_prediction = prediction[0][0]
else:
    scaled_prediction = 1 - (prediction[0][0] - 0) * (1 - 0.5) / (0.5 - 0)
    predicted_class = "Patient"
    scaled_prediction = scaled_prediction

# Create a new dataframe with the predicted class and scaled prediction
results_df_NeuNet = pd.DataFrame({'Category': [predicted_class],
                           'Percentage': [scaled_prediction]})
print(results_df_NeuNet)

  Category  Percentage
0  Patient    0.935931


Code for calculating score of healthy or patient prediction

In [64]:
# create the dataframe
data = {'Category': ['Patient', 'Patient', 'Healthy', 'Patient', 'Patient', 'Healthy'],
        'Score': [0.666667, 0.533333, 0.689576, 0.956667, 0.730333, 0.889576]}
df = pd.DataFrame(data)

# identify the categories with low and high occurrence
low_cat = df['Category'].value_counts().idxmin()
high_cat = df['Category'].value_counts().idxmax()

# compute the sum of score in the low_cat and high_cat
low_cat_sum = df.loc[df['Category'] == low_cat, 'Score'].sum()
high_cat_sum = df.loc[df['Category'] == high_cat, 'Score'].sum()

# compute the difference between high_cat_sum and low_cat_sum
difference = (high_cat_sum - low_cat_sum)/3 * 100

print("Sum of scores in {} category: {}".format(low_cat, low_cat_sum))
print("Sum of scores in {} category: {}".format(high_cat, high_cat_sum))
print("Difference between {} and {} categories: {}".format(high_cat, low_cat, difference))


Sum of scores in Healthy category: 1.5791520000000001
Sum of scores in Patient category: 2.887
Difference between Patient and Healthy categories: 43.59493333333333


In [65]:
difference

43.59493333333333

In [67]:
difference = (high_cat_sum - low_cat_sum)/3 * 100
rounded_difference = "{:.2f}".format(difference)
rounded_difference

'43.59'

# Predict the outcome of the df3 data frame
prediction = new_model.predict(df3)
print(prediction[0][0])

if prediction[0][0] > 0.5:
    predicted_class = "Healthy"
else:
    scaled_prediction = 1 - (prediction[0][0] - 0) * (1 - 0.5) / (0.5 - 0)
    predicted_class = "Patient"
scaled_prediction = scaled_prediction
print("The predicted class is: " + predicted_class + ", and the values in Neural Network is: " + str(scaled_prediction))


# Predict the outcome of the df3 data frame
prediction = new_model.predict(df3)
print (prediction [0][0])

if prediction[0][0] > 0.5:
    predicted_class = "Healthy"
else:
    predicted_class = "Patient"

prediction_value = prediction[0][0]

if prediction_value <= 0.5:
    # Scale the prediction value between 0 to 0.5
    scaled_value = 1 - (prediction_value / 0.5)
else:
    # Scale the prediction value between 0.5 to 1
    scaled_value = (prediction_value - 0.5) / 0.5

# Output the scaled value
#print("The scaled value is:", scaled_value)
print("The predicted class is: " + predicted_class + ", and the values in Neural Network is: " + str(scaled_value))


In [22]:
y_pred = new_model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 0s/step
[[1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]]


In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[34  9]
 [ 2 12]]


0.8070175438596491