# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
%cd Z:\PPMI_Data\Excels\CollaborativeFiltering
df = pd.read_csv('Feats45_unCateg_APPRDX.csv')
df.shape
df.head(2)
# Removing a column
dataset = df.drop(['PATNO', 'Patient_ID'], axis = 1)
dataset.head(2)

Z:\PPMI_Data\Excels\CollaborativeFiltering


APPRDX  Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  Constipate  \
0       1        1       0   12.16      7          1         1           1   
1       1        1       1    7.76      6          1         1           0   

   Depress  DopaDefic  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
0        1          0  ...        57         1           0     45     59   
1        0          0  ...        36         1           3     40     39   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
0          47.5             110             204     17      1  
1          52.0              27              52      9      0  

[2 rows x 46 columns]

In [4]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [5]:
print(X)

[[  1.     0.    12.16 ... 204.    17.     1.  ]
 [  1.     1.     7.76 ...  52.     9.     0.  ]
 [  0.     0.    13.49 ... 252.    26.     0.  ]
 ...
 [  0.     0.    14.18 ...  48.    38.     1.  ]
 [  0.     0.    11.06 ... 106.    32.     1.  ]
 [  0.     0.    11.06 ...  80.    38.     0.  ]]


In [6]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [8]:
y_train = y_train-1

In [9]:
y_test = y_test-1

In [10]:
y_test

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7203 - accuracy: 0.5550
Epoch 2/100
20/20 [==============================] - 0s 822us/step - loss: 0.6904 - accuracy: 0.6100
Epoch 3/100
20/20 [==============================] - 0s 824us/step - loss: 0.6676 - accuracy: 0.6400
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6465 - accuracy: 0.6650
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6275 - accuracy: 0.6950
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6093 - accuracy: 0.7050
Epoch 7/100
20/20 [==============================] - 0s 822us/step - loss: 0.5903 - accuracy: 0.7050
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5737 - accuracy: 0.7150
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5559 - accuracy: 0.7300
Epoch 10/100
20/20 [==============================] - 0s 822us/step - loss: 0.5402 - accuracy: 0.7250
E

20/20 [==============================] - 0s 822us/step - loss: 0.0744 - accuracy: 0.9900
Epoch 83/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0731 - accuracy: 0.9900
Epoch 84/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0718 - accuracy: 0.9900
Epoch 85/100
20/20 [==============================] - 0s 822us/step - loss: 0.0705 - accuracy: 0.9900
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0696 - accuracy: 0.9900
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0684 - accuracy: 0.9900
Epoch 88/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0675 - accuracy: 0.9900
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0662 - accuracy: 0.9900
Epoch 90/100
20/20 [==============================] - 0s 822us/step - loss: 0.0652 - accuracy: 0.9900
Epoch 91/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0642 - accuracy: 0.9900
Epoch 9

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 0s/step
[[0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29  2]
 [ 7 12]]


0.82

## Save model

In [20]:
# Save model
ann.save("model_ann.h5")

In [21]:
ann.history

## Load an empty dataset

In [24]:
df2 = pd.read_csv('NonMotor_AllOne_5values.csv')
# Removing a column
df3 = df2.drop('Patient_ID', axis = 1)
df3.head(2)

Anxiety  Apathy  Benton  Clock  Cognition
0        1       1       1      1          1

### Scale Transformation

In [31]:
df3 = sc.transform(df3)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


ValueError: X has 5 features, but StandardScaler is expecting 45 features as input.

# Perform Transfer Learning

In [27]:
input_layer = tf.keras.Input(shape=df3.shape[1:])
x = input_layer
# Load a pre-trained model
from tensorflow.python.keras.models import load_model
model = load_model("model_ann.h5")

# Freeze the layers in the pre-trained model, only new input will be trained
for layer in model.layers[:-1]:
    layer.trainable = False

# Add a custom classifier on top of the pre-trained model
x = input_layer
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(1024, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
predictions = tf.keras.layers.Dense(1, activation='sigmoid')(x)

# Create a new model using the custom input layer and the custom classifier
model = tf.keras.models.Model(inputs=input_layer, outputs=predictions)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [30]:
prediction = model.predict(df3)
if prediction[0][0] > 0.5:
    predicted_class = "Patient"
else:
    predicted_class = "Healthy"

# Output the result to the user
print("The predicted class is:", predicted_class)

1/1 [==============================] - 0s 16ms/step
The predicted class is: Patient


The 0.5 in the line x = tf.keras.layers.Dropout(0.5)(x) is the rate of dropout, meaning that on average, during training, half of the neurons will be randomly dropped out (i.e., ignored), forcing the network to be more robust and prevent overfitting. Dropout is a common regularization technique for deep learning models. The value 0.5 is a common default for the dropout rate, but this value can be tuned based on the specifics of the problem and the data.

The number 1024 in the dense layer represents the number of neurons/units in the layer. It is a hyperparameter that can be tuned to optimize the performance of the model. The activation function used in this layer is 'relu' (rectified linear unit) which is a popular activation function used in deep learning models. The purpose of using this activation function is to introduce non-linearity in the model, allowing it to learn more complex representations of the data.b

The size of the dense layer, in this case 1024, is a hyperparameter that can be tuned. The number of neurons in the dense layer can have an impact on model performance, with too few neurons leading to underfitting and too many neurons leading to overfitting.

The number of neurons in the dense layer can be increased when the model needs to capture more complex relationships between the input and output. This can happen when the input data is high dimensional, has a large number of features, or when the relationship between the input and output is non-linear. Increasing the number of neurons in the dense layer can also improve model performance when the model has low capacity, meaning that it is not able to fit the data well with a small number of neurons.

On the other hand, the number of neurons in the dense layer can be decreased when the model is overfitting, meaning that it is fitting the training data too well and is not generalizing well to new data. Decreasing the number of neurons in the dense layer can simplify the model and help it to generalize better to new data.

Ultimately, the optimal number of neurons in the dense layer depends on the specific task and data, and finding the right number can require some trial and error. It is common to use techniques such as cross-validation and grid search to find the best hyperparameters for a particular task.

x = tf.keras.layers.Flatten()(x) is a line of code that uses the Flatten layer from TensorFlow's tf.keras API. The purpose of this layer is to flatten the input tensor into a 1D array.

Before flattening, the input tensor might have multiple dimensions (such as height, width, and depth dimensions in a convolutional neural network). The Flatten layer takes in this tensor and reshapes it into a 1D array, which is then used as input to the next layer in the model.