# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from numpy import loadtxt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [2]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
%cd Z:\PPMI_Data\Excels\CollaborativeFiltering
df = pd.read_csv('Feats45_unCategAge_APPRDX.csv')
# Removing a column
dataset = df.drop(['PATNO', 'Patient_ID','Age'], axis = 1)
dataset = dataset.add(1)
dataset.insert (1, 'Age', df ['Age'])
print(dataset.shape)
dataset.head(2)

Z:\PPMI_Data\Excels\CollaborativeFiltering
(250, 47)


APPRDX        Age  Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  \
0       2  67.578082        2       1   13.16      8          2         2   
1       2  46.965716        2       2    8.76      7          2         2   

   Constipate  Depress  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
0           2        2  ...        58         2           1     46     60   
1           1        1  ...        37         2           4     41     40   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
0          48.5             111             205     18      2  
1          53.0              28              53     10      1  

[2 rows x 47 columns]

### Making APPRDX values from 1 & 2 to 0 & 1

In [4]:
dataset.loc[:, "APPRDX"] = df["APPRDX"].apply(lambda x: x - 1)
dataset.head(2)

APPRDX        Age  Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  \
0       0  67.578082        2       1   13.16      8          2         2   
1       0  46.965716        2       2    8.76      7          2         2   

   Constipate  Depress  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
0           2        2  ...        58         2           1     46     60   
1           1        1  ...        37         2           4     41     40   

   Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
0          48.5             111             205     18      2  
1          53.0              28              53     10      1  

[2 rows x 47 columns]

In [5]:
dataset.tail(2)

APPRDX        Age  Anxiety  Apathy  Benton  Clock  Cognition  COGSTATE  \
248       1  66.383562        1       1   12.06      8          1         2   
249       1  68.073973        1       1   12.06      8          1         2   

     Constipate  Depress  ...  Semantic  SleepDay  SleepNight  STAIA  STAIS  \
248           1        1  ...        50         3           2     46     47   
249           1        2  ...        58         1           4     45     46   

     Symbol_Digit  Trail_Making_A  Trail_Making_B  UPSIT  Urine  
248     46.830002              37             107     33      2  
249     51.000000              31              81     39      1  

[2 rows x 47 columns]

In [6]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [7]:
print(X)

[[ 67.57808219   2.           1.         ... 205.          18.
    2.        ]
 [ 46.965716     2.           2.         ...  53.          10.
    1.        ]
 [ 73.96355266   1.           1.         ... 253.          27.
    1.        ]
 ...
 [ 58.26037129   1.           1.         ...  49.          39.
    2.        ]
 [ 66.38356164   1.           1.         ... 107.          33.
    2.        ]
 [ 68.0739726    1.           1.         ...  81.          39.
    1.        ]]


In [8]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [10]:
y_test

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

### Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

ann.add(tf.keras.layers.Dense(units=20, activation='relu'))

### Adding the second hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [26]:

# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(46,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu', kernel_regularizer=tf.keras.regularizers.l1(0.01)))
#ann.add(tf.keras.layers.Dropout(0.1))
ann.add(tf.keras.layers.Dense(units=5, activation='relu', kernel_regularizer=tf.keras.regularizers.l1(0.01)))
#ann.add(tf.keras.layers.Dropout(0.1))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [27]:
model.fit(X_train, y_train, batch_size = 25, epochs = 100)

Epoch 1/100
8/8 [==============================] - 0s 1ms/step - loss: 1.5549 - accuracy: 0.6550
Epoch 2/100
8/8 [==============================] - 0s 1ms/step - loss: 1.2101 - accuracy: 0.5450
Epoch 3/100
8/8 [==============================] - 0s 1ms/step - loss: 1.0310 - accuracy: 0.6600
Epoch 4/100
8/8 [==============================] - 0s 0s/step - loss: 0.8627 - accuracy: 0.6650
Epoch 5/100
8/8 [==============================] - 0s 0s/step - loss: 0.8224 - accuracy: 0.6600
Epoch 6/100
8/8 [==============================] - 0s 0s/step - loss: 0.7529 - accuracy: 0.6900
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7316 - accuracy: 0.6900
Epoch 8/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7048 - accuracy: 0.7100
Epoch 9/100
8/8 [==============================] - 0s 0s/step - loss: 0.6946 - accuracy: 0.7100
Epoch 10/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6696 - accuracy: 0.7100
Epoch 11/100
8/8 [===============

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [28]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 0s/step
[[0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29  2]
 [ 6 13]]


0.84

In [15]:
has_dropout = False
for layer in ann.layers:
    if isinstance(layer, tf.keras.layers.Dropout):
        has_dropout = True
        break
if has_dropout:
    print("Model has dropout layers.")
else:
    print("Model does not have dropout layers.")


Model does not have dropout layers.


In [16]:
has_regularization = False
for layer in ann.layers:
    if isinstance(layer, tf.keras.layers.Dense):
        if layer.kernel_regularizer is not None or layer.bias_regularizer is not None:
            has_regularization = True
            break
if has_regularization:
    print("Model has regularization.")
else:
    print("Model does not have regularization.")


Model has regularization.


## Save model

In [31]:
# Save model
model.save("model_ann.h5")

In [30]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 12)                564       
                                                                 
 dense_10 (Dense)            (None, 8)                 104       
                                                                 
 dense_11 (Dense)            (None, 1)                 9         
                                                                 
Total params: 677
Trainable params: 677
Non-trainable params: 0
_________________________________________________________________
